[package]
name = "pg_query_rust"
version = "0.1.0"
edition = "2018"

[build-dependencies]
bindgen = "0.59.1"
prost-build = "0.9.0"

[dependencies]
bytes = "1.1.0"
prost = "0.9.0"
prost-types = "*" # FIXME
thiserror = "1.0.30"

[dev-dependencies]
serde_json = "*"
